"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERC20Faucet__factory = exports.ChickenBondManager__factory = exports.BondNFT__factory = exports.BNECTToken__factory = exports.BNECTLPZap__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var BNECTLPZap__factory_1 = require("./BNECTLPZap__factory");
Object.defineProperty(exports, "BNECTLPZap__factory", { enumerable: true, get: function () { return BNECTLPZap__factory_1.BNECTLPZap__factory; } });
var BNECTToken__factory_1 = require("./BNECTToken__factory");
Object.defineProperty(exports, "BNECTToken__factory", { enumerable: true, get: function () { return BNECTToken__factory_1.BNECTToken__factory; } });
var BondNFT__factory_1 = require("./BondNFT__factory");
Object.defineProperty(exports, "BondNFT__factory", { enumerable: true, get: function () { return BondNFT__factory_1.BondNFT__factory; } });
var ChickenBondManager__factory_1 = require("./ChickenBondManager__factory");
Object.defineProperty(exports, "ChickenBondManager__factory", { enumerable: true, get: function () { return ChickenBondManager__factory_1.ChickenBondManager__factory; } });
var ERC20Faucet__factory_1 = require("./ERC20Faucet__factory");
Object.defineProperty(exports, "ERC20Faucet__factory", { enumerable: true, get: function () { return ERC20Faucet__factory_1.ERC20Faucet__factory; } });
